import clsx from 'clsx'
import { Grandstander, Inter, Nova_Mono } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const grandstander = Grandstander({
  subsets: ['latin'],
  variable: '--font-grandstander',
})
const novaMono = Nova_Mono({
  subsets: ['latin'],
  variable: '--font-nova-mono',
  weight: '400',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.variable,
          grandstander.variable,
          novaMono.variable,
        )}
      >
        {children}
      </body>
    </html>
  )
}
